user_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /user

login:
    path:     /login
    defaults: { _controller: "UserBundle:Security:login" }

user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }