services:
    user.form:
        class: UserBundle\Form\UserType
        arguments: ['%security.role_hierarchy.roles%']
        tags: [form.type]
# @security.role_hierarchy.roles
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
